// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQqwckQ5qS3Mzd4y6FUA1xYa477SqppdU',
    appId: '1:92848127204:web:d6b38e984bbc7b1465c0f1',
    messagingSenderId: '92848127204',
    projectId: 'pos-casher',
    authDomain: 'pos-casher.firebaseapp.com',
    databaseURL: 'https://pos-casher.firebaseio.com',
    storageBucket: 'pos-casher.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu9Uya0r5EY1cZpkClohaNVjRrhCrAdMs',
    appId: '1:92848127204:android:dd5f7e34b204810765c0f1',
    messagingSenderId: '92848127204',
    projectId: 'pos-casher',
    databaseURL: 'https://pos-casher.firebaseio.com',
    storageBucket: 'pos-casher.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNbCUCRJTqzbr6knUQAERMAV5mugCZTGQ',
    appId: '1:92848127204:ios:f413f34d83c81cab65c0f1',
    messagingSenderId: '92848127204',
    projectId: 'pos-casher',
    databaseURL: 'https://pos-casher.firebaseio.com',
    storageBucket: 'pos-casher.appspot.com',
    iosClientId: '92848127204-rsnjegshkj9rco2a93ajm3fhagua62kv.apps.googleusercontent.com',
    iosBundleId: 'com.abdallahmahmoud.troylab',
  );
}
